version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  jest:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - jest
  scheduled-workflow:
    triggers:
      - schedule:
          cron: '0 * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - jest
